services:
  database:
    image: postgres:latest
    container_name: processos
    restart: always
    environment:
      - POSTGRES_DB=processos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
