spring.application.name=processos

spring.datasource.url=jdbc:postgresql://localhost:5432/processos
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

logging.level.liquibase=TRACE